src/annotation.ts, src/bend.ts, src/chordsymbol.ts, src/element.ts, src/factory.ts, src/flow.ts, src/frethandfinger.ts, src/modifier.ts, src/pedalmarking.ts, src/stave.ts, src/staveconnector.ts, src/staveline.ts, src/staverepetition.ts, src/stavesection.ts, src/stavetempo.ts, src/stavetext.ts, src/stavetie.ts, src/stavevolta.ts, src/stringnumber.ts, src/strokes.ts, src/tables.ts, src/tabslide.ts, src/textbracket.ts, src/textnote.ts, src/tickable.ts, tests/font_tests.ts, tests/stave_tests.ts, tests/staveconnector_tests.ts
Fixes #17 
Once again in review, sorry for the misunderstanding. Previous review comments in #12 already pushed.
=> element (v5)

src/element.ts
=> fix element comments

src/bend.ts, src/element.ts, src/frethandfinger.ts, src/typeguard.ts, src/vibrato.ts, tests/chordsymbol_tests.ts
Issues were caught with eslint and visual inspection.
=> Clean up unused imports and formatting issues.

src/articulation.ts, src/element.ts, src/tables.ts, tests/articulation_tests.ts
Articulations using font. Minor visual differences.
=> articulation (v5)

src/stavetempo.ts, src/tables.ts
Adding a new case with lot of code saving and also visual differences.
=> stavetempo (v5)

src/frethandfinger.ts, src/tables.ts
=> frethandfinger (v5)

src/accidental.ts, src/keysignature.ts, src/ornament.ts, src/tables.ts
@ronyeh following your comment I have divided https://github.com/vexflow/vexflow/pull/32 into smaller parts.
This one is keysignature only. Visual differences:
- Signatures a little more compact.
- Special cases for combination with natural removed.
=> keysignature (v5) - extracted from stavemodifier (v5)

src/stavesection.ts
Minor changes, rect is better aligned.
current
reference
=> stavesection (v5)

src/stavemodifier.ts
Now that the extracts have been merged there is only one file changed and no visual differences!
=> stavemodifier (v5)

src/fonts/common_metrics.ts, src/pedalmarking.ts, src/tables.ts, tests/font_tests.ts
PedalMarking ported with visual differences.
=> pedalmarking (v5)

src/annotation.ts, src/formatter.ts, src/ornament.ts, src/stave.ts, src/staveline.ts, src/tables.ts, src/textbracket.ts
=> notes refactoring preparation extracted from Notes (v5)

src/clef.ts, src/clefnote.ts, src/element.ts, src/notehead.ts, src/stave.ts, src/stavemodifier.ts, src/stavesection.ts, src/stavetempo.ts, src/system.ts, src/timesignature.ts
No visual diferencies, once merged I will rebase #34 and the number of modified files will decrease.
=> element x y integration, extracted from Note (v5).

src/tables.ts, src/textdynamics.ts, src/textnote.ts, tests/textnote_tests.ts
TextNote and TextDynamics ported.
=> textnote (v5)

package.json
=> Moved font dependencies to devDependencies.

src/font.ts, src/note.ts, src/notehead.ts, src/stavenote.ts, src/tables.ts
Minimal visual changes on stavenotes
=> notehead (v5) extracted from note (v5)

src/fonts/common_metrics.ts, src/staverepetition.ts, src/tables.ts
=> staverepetition (v5)

src/fonts/common_metrics.ts, src/note.ts, src/parenthesis.ts
Minimal visual differences:
current
reference
=> parenthesis (v5)

src/stavevolta.ts, src/tables.ts
StaveVolta reworked. Minimal changes on font.
Fixes #11
=> stavevolta (v5)

src/canvascontext.ts, src/fonts/common_metrics.ts, src/rendercontext.ts, src/strokes.ts, src/svgcontext.ts, src/tables.ts
Stroke (v5). This was more complex because it required rotation of glyphs.
=> stroke (v5)

src/font.ts, src/formatter.ts, src/gracetabnote.ts, src/svgcontext.ts, src/tables.ts, tests/articulation_tests.ts, tests/font_tests.ts, tests/formatter_tests.ts, tests/multimeasurerest_tests.ts, tests/percussion_tests.ts, tests/staveline_tests.ts, tests/vexflow_test_helpers.ts, tests/vibrato_tests.ts
Lots of visual differences due to font changes.
=> common metrics fonts

src/svgcontext.ts
Looking further into the measure text details, I found that two classes were still using the method from SVGContext.
I have reworked it to use element and the good news is that it is quicker withour the need of cache.
=> profile - measure text with element

src/bend.ts, src/chordsymbol.ts, src/keysignature.ts, src/multimeasurerest.ts, src/ornament.ts, src/pedalmarking.ts, src/stave.ts, src/staveconnector.ts, src/stavetempo.ts, src/stemmablenote.ts, src/strokes.ts, src/tabnote.ts, src/textbracket.ts, src/textnote.ts, src/timesignature.ts, src/tuplet.ts, tests/chordsymbol_tests.ts, tests/formatter_tests.ts, tests/key_clef_tests.ts, tests/keysignature_tests.ts, tests/ornament_tests.ts, tests/stringnumber_tests.ts
I missed to remove a lot of calls. No visual differences.
=> call to measure text removed

src/stavenote.ts, src/tables.ts
Include changes in:
https://github.com/0xfe/vexflow/pull/1590
https://github.com/0xfe/vexflow/pull/1596
no visual differences
@mscuthbert now both in vexflow 5
=> Vexflow4 1590 1596

src/glyphs.ts, tools/fonts/glyph_codes.js
Skip alternate code points.
Also avoid non-breaking spaces in the description fields.
=> Fix https://github.com/vexflow/vexflow/issues/109

src/timesignature.ts
=> fix musejazz time signature

package-lock.json, src/element.ts, src/gracenote.ts, src/gracetabnote.ts, src/keysignature.ts, src/metrics.ts, src/note.ts, src/notehead.ts, src/stavenote.ts, src/stemmablenote.ts, src/tabnote.ts, src/textdynamics.ts, src/tremolo.ts
Minor non visible changes in demo bach
=> font scale inluded in metrics

tools/fonts/inspector/glyphs.html
I have divided the main canvas into single ones, this allows to add a search function in the future.
The alternate codes are now also dispalyed.
=> alternate codepoints

README.md, demos/fonts/README.md, demos/fonts/all.html, demos/fonts/async-await.html, demos/fonts/async-promise.html, demos/fonts/bravura-score.html, demos/jsfiddle/sandbox.html, demos/modules/module.html, demos/node/canvas.js, demos/node/import2.mjs, demos/node/legacy.js, demos/node/pdf-canvas.js, demos/node/require1.js, demos/worker/worker-vexflow-core.js, demos/worker/worker-vexflow.js, entry/vexflow-debug-with-tests.ts, entry/vexflow-debug.ts, entry/vexflow.ts, src/flow.ts, src/font.ts, src/tables.ts, tests/flow.html, tests/font_tests.ts, tests/vexflow_test_helpers.ts
I renamed some methods and constants to make it simpler and clearer.
This is extracted from https://github.com/vexflow/vexflow/pull/98 to make it easier to review.
=> Font API naming

.eslintrc, tests/flow.html, tests/vexflow_test_helpers.ts, tools/generate_images.js, tools/generate_images_jsdom.js, tools/generate_images_pptr.js, tsconfig.tools.json
Fix https://github.com/vexflow/vexflow/issues/147
Also adds Sebastian and Leipzig as test fonts.
=> Fix `grunt test:reference`

src/element.ts, tests/key_clef_tests.ts, tests/keysignature_tests.ts, tests/ornament_tests.ts, tests/stringnumber_tests.ts
fix #76
static function to measure text/glyphs as requested in #76  
No visual differences.
=> getElementWidth added

src/chordsymbol.ts, src/multimeasurerest.ts, src/pedalmarking.ts, src/repeatnote.ts, src/staveconnector.ts, src/stavenote.ts, src/staverepetition.ts, src/strokes.ts, src/tables.ts, src/tabnote.ts, src/textdynamics.ts, src/textnote.ts, src/tremolo.ts, src/tuplet.ts, tests/articulation_tests.ts, tests/formatter_tests.ts, tests/glyphnote_tests.ts
Now using Glyphs. No visual differences.
=> glyphs constants

.eslintignore, .eslintrc, Gruntfile.js, demos/entry/vexflow-bravura.esm.html, demos/entry/vexflow-core.esm.html, demos/entry/vexflow.esm.html, entry/vexflow-bravura.ts, package.json, src/gracenote.ts, src/note.ts, src/staverepetition.ts, src/stavetempo.ts, src/stringnumber.ts, tests/annotation_tests.ts, tests/articulation_tests.ts, tests/gracetabnote_tests.ts, tests/qunit/qunit.css, tests/qunit/qunit.js, tests/rests_tests.ts, tests/tabslide_tests.ts, tests/tabtie_tests.ts
Small improvements and fixes on top of the recently merged VexFlow.* API PR.
More demos.
Automatically fix errors with eslint when `grunt` is run.
=> VexFlow.* API

src/curve.ts, src/element.ts, src/svgcontext.ts, tests/curve_tests.ts
intial step to support #157 
it also reesolves the deep copy in svgcontext.
no visual changes
=> linedash support

tests/vexflow_test_helpers.ts
@ronyeh the tests are taking too long. I believe that at this stage we can test with bravura only.
=> bravura only tests

src/bend.ts
Refactored to use the Element Style infrastructure. I changed all to black.
current
reference
=> Element Style refactored: Bend

src/annotation.ts, src/articulation.ts, src/chordsymbol.ts, src/clef.ts, src/element.ts, tests/accidental_tests.ts, tests/annotation_tests.ts, tests/articulation_tests.ts, tests/chordsymbol_tests.ts, tests/clef_tests.ts, tests/stavenote_tests.ts, tests/vexflow_test_helpers.ts
I have started with tests and fixes for bounding boxes and I have found already a bug in Element.
Let us review and merge this group and follow on other PRs with the next derivates from Element.
No visual differences. Only new tests to check the bounding boxes.
=> bounding box fixes

demos/opentype/canvas.html
See https://www.npmjs.com/package/@vexflow-fonts/gonville
=> Adjusted origins of Gonville glyphs. 

package.json
Fixes [#181](https://github.com/vexflow/vexflow/issues/181)
=> Remove *.ts source files from the npm package.

src/clefnote.ts, src/glyphnote.ts, src/note.ts, tests/clef_tests.ts, tests/glyphnote_tests.ts
No visual differences. New tests added
=> glyphnote & clefnote bounding box

.github/workflows/ci-workflow.yaml
=> Run lint in workflow

src/stavenote.ts, tests/accidental_tests.ts
fixes #210 
Minor code fix.
Accidental padding test modified to show fix
=> fix unison notehead accidental collision with stems down

src/stavenote.ts, tests/accidental_tests.ts
@mscuthbert your comments are now in.
=> review comments

src/svgcontext.ts
fixes #202 
@AaronDavidNewman can you suggest a test?
There are no visual differences.
=> fix clear, no scale required

src/bend.ts, src/element.ts, src/metrics.ts, src/notehead.ts, src/pedalmarking.ts, src/stemmablenote.ts, tests/accidental_tests.ts
just lint automatic changes, no vissual changes.
=> lint fixes

src/curve.ts, src/factory.ts, tests/curve_tests.ts
fixes #205 bullet 1 & 2 I do not know how to proceed with 3.
New test for opening direction
=> fix curve api

src/annotation.ts, src/barnote.ts, src/beam.ts, src/bend.ts, src/chordsymbol.ts, src/clef.ts, src/curve.ts, src/element.ts, src/glyphnote.ts, src/keysignature.ts, src/ornament.ts, src/stave.ts, src/stavebarline.ts, src/staveline.ts, src/stavenote.ts, src/stavetie.ts, src/stem.ts, src/tabnote.ts, src/textnote.ts, src/timesignature.ts
Fixes #194 
This is the proposal that I described in #194
No visual differences.
=> Issue194 - ctx.applyStyle()/removeStyle() should always push a state

README.md
just a readme update with focus on releasing
=> readme update for release

src/metrics.ts, src/stave.ts, src/stavesection.ts, tests/stave_tests.ts
fixes #63 
Not required for 5.0
Visual differences
current (section B with extra padding)
reference
=> StaveSection with configurable padding

src/articulation.ts
fixes #254
calculation movved from draw to format
no visual differences
=> Draw idempotent on Articulation

README.md, demos/entry/vexflow-bravura.esm.html, demos/entry/vexflow-bravura.html, demos/entry/vexflow-core.esm.html, demos/entry/vexflow-core.html, demos/entry/vexflow-debug-with-tests.html, demos/entry/vexflow-debug.html, demos/entry/vexflow.esm.html, demos/entry/vexflow.html, demos/modules/module.html, demos/modules/script-tag.html, tests/stavenote_tests.ts, tests/unison_tests.ts
Per https://github.com/vexflow/vexflow/discussions/278
See parallel PRs at
* https://github.com/vexflow/vexflow-examples/pull/14 
* https://github.com/vexflow/vexflow-sandbox/pull/2
=> Update documentation to use factory not vf

src/annotation.ts, src/beam.ts, src/chordsymbol.ts, src/clef.ts, src/element.ts, src/flag.ts, src/glyphnote.ts, src/keysignature.ts, src/metrics.ts, src/notehead.ts, src/ornament.ts, src/stave.ts, src/stavebarline.ts, src/stavenote.ts, src/stavetie.ts, src/tabnote.ts, src/timesignature.ts, src/timesignote.ts, src/tuplet.ts
This is just a proposal for the implementation in Element. Please feedback on approach.
Basicly:
- implementation in Element
- call once closeGroup is called
I have doubts where to configure, metrics?
=> pointer rect 

package.json, src/tickable.ts, src/tuplet.ts
Implement #285
Don't merge until there's consensus on #285 (or no one seems to care)
Bump to 5.1 because this does have actual backwards incompatibility concerns.
All visual tests pass w/o regressions
=> Tuplet refactor
