vexflow/vexflow

tools/get_releases.mjs

The `grunt get:releases:4.2.2` script used to work fine, but perhaps some versions of `npm pack` do not create the directory for you if it doesn't already exist.
This patch fixes the script, to allow for easier visual diffing between our current work and a release that has been published on NPM.
**This patch will also be applied to the 4.x repository** at https://github.com/0xfe/vexflow to help address the PR on visual regression testing: https://github.com/0xfe/vexflow/issues/1508

Fix: create the temporary directory for downloading NPM releases.

---

src/annotation.ts
src/bend.ts
src/chordsymbol.ts
src/element.ts
src/factory.ts
src/flow.ts
src/frethandfinger.ts
src/modifier.ts
src/pedalmarking.ts
src/stave.ts
src/staveconnector.ts
src/staveline.ts
src/staverepetition.ts
src/stavesection.ts
src/stavetempo.ts
src/stavetext.ts
src/stavetie.ts
src/stavevolta.ts
src/stringnumber.ts
src/strokes.ts
src/tables.ts
src/tabslide.ts
src/textbracket.ts
src/textnote.ts
src/tickable.ts
tests/font_tests.ts
tests/stave_tests.ts
tests/staveconnector_tests.ts

Here we go...
`Element` is the base of vexflow 5. An `Element` has a member `text` which is a series of unicode characters (including SmufL codes). This text is drawn using the `textFont` which is normally a comma separated list of fonts. Element calls internally `measureText` to calculate the `metrics`, `height` and `ẃidth` of the `text`
`renderText` will render the `text` using the context provided at the coordinates provided. Internally `Element` will apply the `xShift` and `yShift`. 
So far no visual differences. The default fonts are moved to `commonMetrics`.

element (v5)

---

Gruntfile.js
package.json
tests/flow.html
tests/formatter/index.html

The most important changes are in Gruntfile.js and package.json. For example:
```
pushRepo: 'git@github.com:vexflow/vexflow.git',
```
This will allow our release script and NPM to reference the correct VexFlow 5+ repo.

Update repo URLs from `0xfe/vexflow` to `vexflow/vexflow` to make the release script push to the correct repository.

---

tools/fonts/inspector/glyphs.html

This inspector helps a lot to see the difference between glyphs as the position of them stay the same when selecting another font.
Just a tool update, no visual differences.

glyph inspector using fonts directly

---

src/factory.ts
src/vibrato.ts
src/vibratobracket.ts
tests/vibrato_tests.ts
tests/vibratobracket_tests.ts

I have decided to add some fun with a second topic: vibratos.
SMuFL defines a lot of them and now it is possible to use them, see https://w3c.github.io/smufl/latest/tables/multi-segment-lines.html?highlight=vibrato#multi-segment-lines-ueaa0ueb0f
As an example:
On the other side, now it is only possible to use the SMuFL glyphs. The run-time path generated vibratos are now out.

vibrato (v5)

---

Gruntfile.js

Do not build the docs. This makes testing and reviewing PRs for v5 easier.
Eventually we will migrate all the docs to its own repository at: https://github.com/vexflow/vexflow-docs

Skip building the docs.

---

.gitignore
src/chordsymbol.ts
src/flow.ts
src/stavetempo.ts
src/tables.ts

A number of small improvements, including:
- simpler implementation of `lookupMetric()`
- Use `\uXXXX` unicode strings directly to avoid unnecessary String.fromCharCode().
- Call out migration HACKs with a bigger block comment so we can easily search for them later on.

Small Improvements & Cleanup

---

package.json

https://www.npmjs.com/package/vxflw-early-access
Once VexFlow 5 is finalized, we will overwrite the 4.2.x on NPM.

For now, release alpha versions to NPM as `vxflw-early-access`

---

src/flow.ts
src/fonts/load_all.ts
src/fonts/load_musejazz.ts
src/glyph.ts
tests/vexflow_test_helpers.ts

This is a hack to show the progress of the migration. Glyph.ts returns always a minus symbol. Only the elements ported are visble. i.e.: StaveTempos

musejazz hack to show progress

---

src/chordsymbol.ts

Allow a chord change to float over several things notes by disabling horizontal formatting for a chord symbol.  Prevents:

Add getReportWidth to chordsymbol

---

src/tables.ts

Since these are hard-coded strings and have been around for 10 years.

Add ornament codes for backwards compatibility

---

src/clef.ts
src/clefnote.ts
src/font.ts
src/fonts/common_metrics.ts

@ronyeh following your comment I have divided #32 into smaller parts.
This one is clef only. Visual differences:
- slightly smaller clefs
- `fClef8va/b` & `gClef8va/b` glyphs used directly
Note: adding support for `fClef15ma/b` & `gClef15ma/b` is trivial now.

clef (v5) - extracted from stavemodifier (v5)

---

src/factory.ts
src/glyphnote.ts
src/repeatnote.ts
tests/glyphnote_tests.ts

GlyphNote and RepeatNote with minimal visual changes:
current
reference

glyphnote (v5)

---

src/tuplet.ts

Tuplets ported. They are now using the `tuplet0` .. `tuplet9` &`tupletColon` SMuFL codes. 
Visual differences:
Current
Reference

tuplet (v5)

---

src/fonts/common_metrics.ts
src/tables.ts
src/tremolo.ts
tests/tremolo_tests.ts

Big tremolos removed, they are big enough when following the SMuFL ratio. x & y offsets calculated at run time based on the note position. Y position calculated from end of stem.
current
reference

tremolo (v5)

---

src/font.ts
tests/flow.html

Omit the `fontNames` parameter to load all the web fonts compatible with VexFlow.

Use loadWebFonts(fontNames) to load only a few fonts. 

---

src/annotation.ts
src/tables.ts
tests/annotation_tests.ts
tests/beam_tests.ts

Annotations follow now the specified font. Several layout improvements as well.
Some visual changes with Petluma.
current
reference
current
reference
current
reference

annotation (v5)

---

src/factory.ts
tests/key_clef_tests.ts
tests/keysignature_tests.ts
tests/ornament_tests.ts
tests/stringnumber_tests.ts

Visual changes due to the different measure.
current
reference
current
reference

remove glyph in tests

---

src/staveconnector.ts
src/stavetext.ts
src/tables.ts

StaveConnector & StaveText ported. Visual changes:
current
reference

staveconnector (v5)

---

src/font.ts
src/fonts/common_metrics.ts
src/stem.ts
src/stringnumber.ts
src/tables.ts
tests/formatter_tests.ts

Starting with clean up :) 
Visual changes in formatter  text due to the change in width claculation.
current
reference

cleanup - refactor currentMusicFont

---

src/tables.ts
src/textbracket.ts

TextBracket ported. Visual differences:
current
reference
current
reference

textbracket (v5)

---

src/accidental.ts
src/annotation.ts
src/articulation.ts
src/bend.ts
src/chordsymbol.ts
src/clef.ts
src/crescendo.ts
src/element.ts
src/frethandfinger.ts
src/glyphnote.ts
src/multimeasurerest.ts
src/notehead.ts
src/ornament.ts
src/stave.ts
src/staveline.ts
src/stavenote.ts
src/stavesection.ts
src/stavetempo.ts
src/stavetext.ts
src/stavetie.ts
src/stringnumber.ts
src/system.ts
src/textbracket.ts
src/textdynamics.ts
src/textnote.ts
src/timesignature.ts
src/tremolo.ts
src/vibrato.ts
src/voice.ts
tests/mocks.ts

Reworlk to reduce the number of calls to measureText. Now only called when a recalculation is required based on #metricValid. No visual differences
current
reference

measure text reworked

---

Gruntfile.js
src/canvascontext.ts
src/font.ts
src/glyphs.ts
src/multimeasurerest.ts
src/parenthesis.ts
src/pedalmarking.ts
src/rendercontext.ts
src/tables.ts
src/tabnote.ts
src/tremolo.ts
tests/beam_tests.ts
tests/tabnote_tests.ts

I ran eslint and fixed a bunch of issues it highlighted:
```
vexflow/src/canvascontext.ts
118:32  warning  Insert `·`  prettier/prettier
vexflow/src/font.ts
1:10  error  'TupletMetrics' is defined but never used  @typescript-eslint/no-unused-vars
2:10  error  'defined' is defined but never used        @typescript-eslint/no-unused-vars
vexflow/src/glyphs.ts
78:56  error  Irregular whitespace not allowed  no-irregular-whitespace
78:61  error  Irregular whitespace not allowed  no-irregular-whitespace
94:56  error  Irregular whitespace not allowed  no-irregular-whitespace
94:61  error  Irregular whitespace not allowed  no-irregular-whitespace
154:48  error  Irregular whitespace not allowed  no-irregular-whitespace
154:53  error  Irregular whitespace not allowed  no-irregular-whitespace
3591:3 …
```

Run eslint.

---

src/ornament.ts
tests/ornament_tests.ts

Port from https://github.com/0xfe/vexflow/pull/1598
Issue this repository https://github.com/vexflow/vexflow/issues/118
I tried porting it, but the Y coordinate of the turn of the lower voice went down. Can I assume this is an intended change in VexFlow 5?
This change only affects the X coordinate.
**VexFlow 4**
**VexFlow5**

Hotfix ornament delayed draw

---

src/keysignature.ts

Allows to get the width without having an assigned stave.
@ronyeh Request from @jaredjj3 to your question in https://github.com/stringsync/vexml/issues/113

calculate width without stave

---

src/timesignature.ts
tests/timesignature_tests.ts

This is a feature not supported for the informal musicxml test suite higlighted by @jaredjj3. Thanks Jared!
The ´3' is now supported.
For reference https://music.stackexchange.com/questions/66225/what-is-this-time-signature-with-only-one-number

support single digit time signatures

---

src/timesignature.ts

looking at the single number topic I saw that some fonts were not presenting the digits correctly. I also saw that the petaluma numbers were more separated than the others. I have adjusted the threshold and also have shifted half a line rather than a line.

adjust big time signatures

---

src/staveline.ts

Added usage of Element infrastructure. This has revealed a bug. The calculation of the text width was not taking into accout the font.

staveline (v5)

---

src/strokes.ts
tests/strokes_tests.ts

Fixes https://github.com/vexflow/vexflow/issues/91
Rasgueado now uses the wikipedia spelling: https://en.wikipedia.org/wiki/Rasgueado
The previous misspelling only has about 3000 results on Google.

Fix Rasgueado misspelling.

---

src/stavetempo.ts
tests/stave_tests.ts

Features missing detected by @jaredjj3 in https://github.com/stringsync/vexml/pull/157
Tests modified to show the new features:
reference
current

metronome musicxml features

---

src/ornament.ts
tests/ornament_tests.ts

There was no ornament test with low notes. Jared highlighted that they should stay about the Stave. 
I modified a test to lower the notes and Ornament.format to make the ornaments stay above.
Only one difference in the modified test
current
reference
without the modification in Ornament, the ornaments go between lines.

ornaments above stave

---

src/accidental.ts
src/dot.ts
src/element.ts
src/ornament.ts
src/stavenote.ts
tests/stavenote_tests.ts

The topic ibounding box is not complete with this PR but I would like to check with a new alpha release if this goes in the good direction to resolve the issue #155 from @AaronDavidNewman. I have modified the stavenote bounding box test to include an accidental, an ornament and dots. This test is the only visual difference.

fix stavenote bounding box

---

src/notehead.ts

The bounding box of notehead had a bug.
current
reference

notehead: fix bounding box

---

src/canvascontext.ts
src/rendercontext.ts
src/stavenote.ts
src/stem.ts
src/svgcontext.ts
src/tabnote.ts

The solution is to set a transparent pointer rect to capture the events.
No visual differences but right behaviour on the interactive mouseover tests.

Redesign pointer events

---

.gitignore
src/annotation.ts
src/chordsymbol.ts
tests/annotation_tests.ts
tests/chordsymbol_tests.ts

Fixes #178 
All the visual differences are things like this, where the first note was left justified, so it previously got extra space to the left, now it gets it to the right.
Reference:
Current:
Reference:
Current:
Added a new test with very long chord symbols and changed the lyrics test to start with a long lyric, left justified.
Reference:
Current:

Fix Annotation and ChordSymbol justification padding

---

package.json

We can start publishing alpha / beta versions under `vexflow` from now on.

Move package.json project name to `vexflow`.

---

src/stave.ts

A test that each StaveModifier has a draw() method goes back to the pre-ES6 class version of Vexflow and is unnecessary now.
First added way back in 2012 as:
https://github.com/vexflow/vexflow/commit/f5e562519dffd0e5931c136218ab36bbc2cf1cb3
Added a type to remind ourselves that these are StaveModifiers not Modifiers.
Q: Stave().getModifiers returns a different array than Stave.modifiers if position or category is specified, but returns the original array if neither is specified.  I wonder if line 567 should be changed to return [...this.modifiers] so that in all cases `.modifiers` remains immutable?

Remove unneeded test on StaveModifier

---

src/annotation.ts

Minor.
A change to v5 format in  #51 left a comment that is now outdated.  Annotation no longer changes anything in RenderContext except through applyStyle(), so there is no need for an additional ctx.save() or ctx.restore().
https://github.com/vexflow/vexflow/commit/d6c878989e3e7f9723d7fcf63fb039faef7c66df
Fix param typing in setJustification

Annotation - remove outdated comment

---

Gruntfile.js
src/formatter.ts
src/fraction.ts
src/tickcontext.ts

Fixes #187 and implements part of the philosophy of #183.
Fixes the calculation of means by adding a "total" to `Formatter().durationStats` so that mean deviation is calculated properly.
`Formatter().tune()` previously embedded a powerful `move(tickContext, shift)` routine inside it that did not use any scope or `this` variables.  Rewrote as `TickContext().move(shift)`
`Formatter().tune()` calculated the cost of space deviations as `-sumArray(context.getTickables().map((t) => t.getFormatterMetrics().space.deviation));` which does not use any scope or `this` variables.  Moved to `TickContext().getDeviationCost()` (without the negative sign).  Added `TickContext().getAverageDeviationCost()` which I believe would fix a bug that contexts with more tickables are weighed more heavily, but did …

Formatter: mean calculation + pull out algorithms

---

src/accidental.ts
src/beam.ts
src/element.ts
src/fraction.ts
src/modifier.ts
src/multimeasurerest.ts
src/registry.ts
src/stavenote.ts
src/stavetempo.ts
src/svgcontext.ts
src/tickable.ts
src/vibrato.ts
tests/flow-headless-browser.html
tests/vexflow_test_helpers.ts

For many of them I looked up in the past whether they were protected or private (or if they were mentioned in docs) and set protected or private accordingly.  For the rest I used my best judgment about whether I would ever want to query them outside of the system or not.
Fixes #179 
Add runtime tests for two cases where zero-width element would cause infinite loops -- these came up when my code was buggy, but figured it's worth keeping the tests in.
Running visual differences now.

Remove hash from private properties

---

src/stave.ts

I was building a new project that uses Vexflow, and saw a warning from ESBuild.
> [WARNING] The "??" operator here will always return the left operand [suspicious-nullish-coalescing]
```
vexflow/src/stave.ts:659:22:
659 │         widths.left = -layoutMetrics.xMin ?? 0;
╵                       ~~~~~~~~~~~~~~~~~~~
```
>  The left operand of the "??" operator here will never be null or undefined, so it will always be returned. This usually indicates a bug in your code.
The underlined part of the code has a minus `-` that always tries to coerce `layoutMetrics.xMin` into a number; when it's undefined that results in `NaN`, so it never reaches `0`.
To correct this I changed it to:
```js
widths.left = -(layoutMetrics.xMin ?? 0);
```
The warning no longer appears. This seems to be the intended …

Use of nullish coalescing operator with minus

---

src/metrics.ts
tests/tabstave_tests.ts

fixes #207 
Metric defined and TabStave test modified to include measure number.

fix tabstave measure numbers

---

src/pedalmarking.ts
tests/pedalmarking_tests.ts

fixes #204
Changes the pedal markins brackets ends to include the area behind the note. Either to the next note in its voice or the end of the stave.
@mscuthbert is this a right approach?
@jaredjj3 does this fix the vexml issue?
Differences
current
reference
current
reference
current
reference
current
reference
current
reference

Adjust pedalmarkins end

---

src/bend.ts
src/element.ts
src/metrics.ts
src/notehead.ts
src/stave.ts
src/vexflow.ts

This PR is a proposal to resolve #161, it also returns the grey lines to the bends.
My proposal to make the ElementStyle Infrastructure consistent is:
- Include the defaults in `metrics.ts`
- Use `this.style` together with `setStyle()` and `getStyle()` defined on `Element` for derivate classes that require only one style and avoid `render_options` related to style (see `stave.ts`)
- For classes deriving from `Element` that require more than one style, define the additional `styleXXX` (with `getStyleXXX()` and `setStyleXXX()`) in the derived class. (see `bend.ts`)

new element style infrastructure

---

tests/accidental_tests.ts

Removes unused SMuFLS from testes as identified in #200 it also fixes the heigth of the tests images
current

Issue200missingsmufls

---

src/metrics.ts
src/tuplet.ts

fixes #62
Not required for 5.0
Visual differences
current
reference
current
reference

tuplet text position configurable

---

src/annotation.ts
src/bend.ts
src/chordsymbol.ts
src/gracenotegroup.ts
src/ornament.ts
src/stringnumber.ts

This is part of #225:
- avoids duplicated calls to ctx.save on Modifiers
No visual differences.

refactor applyStyle on Modifiers (part of #225)

---

src/gracenotegroup.ts
src/metrics.ts
src/modifier.ts
tests/gracenote_tests.ts

fixes #174 
Not required for 5.0
Accidentals on grace notes have now the same as the notes (see grace notes on note 1 & 4)
It is also allowed to place grace notes on the right (see note 5).
@jaredjj3 does this address your comments?
current
reference

Grace notes accidentals' size and right position

---

src/curve.ts
src/easyscore.ts
src/formatter.ts
src/stavenote.ts
src/stavetie.ts
src/svgcontext.ts
src/tabslide.ts
src/util.ts
tests/accidental_tests.ts
tests/mocks.ts
tests/multimeasurerest_tests.ts
tests/tabslide_tests.ts
tests/tabtie_tests.ts
tests/vexflow_test_helpers.ts

When I ran `grunt eslint` on the most recent version, I get these changes.
Any idea why eslint is removing these directives?
```
// eslint-disable-next-line
```

grunt eslint

---

src/keysignature.ts
tests/keysignature_tests.ts

fixes #121
fixes #131
not required for 5.0
the refactoring has revealed that the bounding box calculation was wrong.
Visual differences:
- first test now includes boundig boxes.
- keysignatures leave a bit more space for other elements in the stave
current
reference

keysignature refactor boundingbox calculations

---

src/barnote.ts
src/clef.ts
src/factory.ts
src/keysignature.ts
src/stave.ts
src/stavebarline.ts
src/stavemodifier.ts
src/staverepetition.ts
src/stavetempo.ts
src/stavetext.ts
src/stavevolta.ts
src/timesignature.ts

Not required for release 5.0
- Removes unnecesary calls to `applyStyle`, `save` and `restore` in `draw`
- Refactors `StaveModifiers.draw` to fit `Element.draw` this is no parameters and no returned value.
No visual changes.

stavemodifiers calling  drawwithstyle (part of #225)

---

src/keysignature.ts

fixes #245
see https://github.com/stringsync/vexml/pull/233

Allow to get width without stave

---

src/tuplet.ts

Fixes #250 grouping suggestion and adds simple pointer rectangle to tuplet as in StemmableNote. If adding the pointer rectangle would cause problems, its an easy delete! 
Also, moved this.setRendered() to the bottom of the class to match where it is placed in StemmableNote.

adding svg grouping to Tuplet draw method

---

src/beam.ts
src/stavenote.ts
src/stemmablenote.ts
src/tables.ts
tests/beam_tests.ts
tests/rests_tests.ts

Updated Vexflow to support **longa**, **maxima**, **256th**, **512th** and **1024th** notes.
List of changes:
• Added respective glyphs for each note (also 128th); 
• Ensured each note has a correct tick number;
• Supported rests (updated rests "basic" test to include all new notes);
• Added l (Longa) and m (Maxima) aliases.
• Updated supported beam durations with 128, 256, 512, 1024.
• Added "mixed3" test on beam_tests.ts which simply renders two beams (one beam per voice) with new notes. I noticed that the last notes in the measure do not get beamed, but it doesn't seem to be caused by the added durations.
As you can see, there is a problem with the last beam notes connection. I checked if I missed something in the updated code, but I couldn't find any problem. Please tell me if I did …

Added longa, maxima, 256th, 512th and 1024th notes support

---

src/stave.ts
src/tables.ts
tests/keysignature_tests.ts

[Original PR ](https://github.com/vexflow/vexflow/pull/256), remade from main V5 branch following comment
This update introduces support for complex key signatures, including theoretical or rare keys from different modes. It enhances versatility and provides additional options for defining key signatures. This implementation preserves backward compatibility, ensuring that all existing key signature definitions and functionality remain unaffected.
1. **Alternative Key Signature Definition:**  
The `addKeySignature` method now accepts a new format, allowing direct specification of the number of flats or sharps:
```javascript
stave.addKeySignature('flats_4');
```
This adds four flats to the key signature, suitable for modes such as Ab major, F minor, Bb Dorian, C Phrygian, Db Lydian, Eb …

Add complex key signatures

---

src/metrics.ts
src/tuplet.ts
tests/tuplet_tests.ts

Hey all, 
I know noncritical PRs are on hold for the moment, but still thought I would get started contributing this. Useful for notation with complex tuplets and Ferneyhough et al love this kind of thing. I have basic centering at the moment but it would be easy enough to change the layout so that the tuplet ratio itself stays centered. Also, did some small quality life improvements by creating constants for some magic numbers that were in the code. 
Very interested to see if anyone has better ideas for how to structure the API. Could it be possible to make this a flag (something like isBeatShown or showBaseDuration) and have the tuplet itself calculate what the baseNoteLength should be? Also, if it stays as an input value, I am assuming there could maybe be a better name. 
I have a …

added optional "helper" note after tuplet ratio

---

README.md

I simplified the README. Since it's the first thing anyone will see, we want the first example to be as simple as possible.
The CJS build of VexFlow comes bundled with Bravura & Academico, so we don't need to specify the CSS `@font-face` or call setFonts. It is done automatically by the library in `entry/vexflow.ts`.

Simplify the README.

---

tests/sandbox.html

Fixes https://github.com/vexflow/vexflow/issues/249
The new VexFlow Sandbox is at: https://vexflow.github.io/vexflow-sandbox/
It allows you to compare V5, V4, V3, V2.
---
This PR adds a `sandbox.html` file to the main vexflow repository.
It wraps the sandbox website in an `<iframe>`, so you can load your local development build of `vexflow-debug.js` into the sandbox.
Change to your `vexflow/` directory, and run `grunt` to make a local build.
Then start a local webserver with `npx http-server` and load up the sandbox at:
<a href="http://127.0.0.1:8080/tests/sandbox.html">http://127.0.0.1:8080/tests/sandbox.html</a>
When you make changes to your local copy, you can just refresh the localhost sandbox to see the new changes.
Questions / Comments?
@rvilarl 
@mscuthbert
There are still some …

VexFlow Sandbox

---

src/tuplet.ts
tests/tuplet_tests.ts

Closes #297 
Uses new algorithm for `getNestedTupletCount()`. Added test case handles when all the children are tuplets. Current test case Nested Tuplets already handles the other scenario where at least one child is not a tuplet.
Added commit to change the render order of the tuplets in nested tuplet and simple tuplet tests to be in line with how they would normally be found in music notation.

new getNestedTupletCount algorithm

---

src/metrics.ts
src/tuplet.ts
tests/tuplet_tests.ts

To allow `getBoundingBox()` to work, I have made the text and suffix elements have the correct bounds information be published during `draw()`. I am treating the tuplet's `this.x`, `this.y`, `this.height`, and `this.width` as the bounds of a potentially drawn bracket. Not sure if this is the best solution... but it allows the three elements (bracket, suffix, and text) to all cleanly store their bounds information to be merged in `getBoundingBox()`.
I believe the tests I added cover all tuplet cases. Happy to answer any questions. 
I also continued to slightly rid the class of magic numbers by moving bracket leg length and bracket line width to metrics.

clean and add bounding box override to tuplet

---

src/annotation.ts
src/beam.ts
src/chordsymbol.ts
src/clef.ts
src/flag.ts
src/glyphnote.ts
src/keysignature.ts
src/notehead.ts
src/ornament.ts
src/stave.ts
src/stavebarline.ts
src/stavenote.ts
src/stavetie.ts
src/stem.ts
src/tabnote.ts
src/timesignature.ts
src/timesignote.ts
src/tuplet.ts

Originally from @rednebmas, but on the old repo: https://github.com/0xfe/vexflow/pull/1656
Actually use the `class` attribute on drawable elements. Currently we can set it with `Element.addClass()` but it is totally ignored at rendering.
The idea is, for instance, to be able to colorize some notes or ease the interactivity with some `Elements`.

Fix svg group: Include class attribute
